### ISSUE TITLE
Ingen respons fra Dataforsyningens plugin - lagoversigt vises

### ISSUE THREAD

**Issue by mathiku** [SDFIdk/Qgis-dataforsyningen#32]
Vi er en del der har problemer med plugin. På den feedback jeg får lyder det som om det er kommet til løbende på det sidste, men ikke er afhængig af QGIS versionen. Jeg har testet alle LTR fra 3.16 og frem med samme resultat.
Fejlen kommer som en Python error hvor det lader til at intet returneres fra URL.

Python Error:
```
2023-09-20T13:32:35     WARNING    Traceback (most recent call last):
              File "C:/Users/DKMK01256/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Dataforsyningen\dataforsyningen.py", line 145, in 
              df_helper = lambda _id: lambda: self.open_df_node(_id)
              File "C:/Users/DKMK01256/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Dataforsyningen\dataforsyningen.py", line 192, in open_df_node
              layer = self.open_node(node, id)
              File "C:/Users/DKMK01256/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Dataforsyningen\dataforsyningen.py", line 195, in open_node
              QgsProject.instance().readLayer(node)
             TypeError: QgsProject.readLayer(): argument 1 has unexpected type 'NoneType'
```

En umildbar mistanke er selvfølgelig at det skyldes et URL der skal white-listes, men burde vel fremgå af fejlbeskeden.

**Comment by JesperKock** [comment]
Hvornår oplever i at fejlen sker?
